site_name: Tetrue Terminal Wiki
nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Managing Lifecycle: user-guide/managing-lifecycle.md
    - Managing Terminal State: user-guide/managing-state.md
    - Drawing Text: user-guide/drawing-text.md
    - Reading Input: user-guide/reading-input.md
    - Color & Styling: user-guide/styling.md
    - Extras:
      - Introduction: user-guide/extras/introduction.md
      - Frame Timing: user-guide/extras/frame-timing.md
  - API Reference: api-reference.md
  - About: about.md
theme:
  name: material
  features:
    content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

plugins:
  - glightbox