/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.bfur64"
version = "3.0.0-SNAPSHOT"

val lanternaVersion = project.properties["lanternaVersion"] as String
val jlineVersion = project.properties["jlineVersion"] as String

tasks.processResources {
    val tetrueTerminalVersion = project.version.toString()
    val lanternaVersion = lanternaVersion
    val jlineVersion = jlineVersion

    inputs.property("tetrueTerminalVersion", tetrueTerminalVersion)
    inputs.property("jlineVersion", jlineVersion)

    filesMatching("io/github/bfur64/terminal/settings.json.template") {
        expand(
            "tetrueTerminalVersion" to tetrueTerminalVersion,
            "lanternaVersion" to lanternaVersion,
            "jlineVersion" to jlineVersion
        )
    }

    rename("(.+)\\.template", "$1")
}

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("com.vanniktech.maven.publish") version "0.36.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // Rendering Pipeline
    implementation("com.googlecode.lanterna:lanterna:${lanternaVersion}")
    implementation("org.jline:jline:$jlineVersion")

    // JSON Reader
    implementation("tools.jackson.core:jackson-databind:3.1.3")

    // Logger
    implementation("org.apache.logging.log4j:log4j-api:2.26.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(group.toString(), "tetrue-terminal", version.toString())

    pom {
        name.set("menu-manager")
        description.set("A meta library that combines JLine and Lanterna for my specific purposes")
        inceptionYear.set("2026")
        url.set("https://github.com/BFUR64/tetrue-terminal")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/license/mit")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("BFUR64")
                name.set("Terrance")
                url.set("https://github.com/BFUR64/")
            }
        }
        scm {
            url.set("https://github.com/BFUR64/tetrue-terminal")
            connection.set("scm:git:https://github.com/BFUR64/tetrue-terminal.git")
            developerConnection.set("scm:git:ssh://git@github.com/BFUR64/tetrue-terminal.git")
        }
    }
}