/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.bfur64"
version = providers.gradleProperty("version").get()

val lanternaVersion: String = providers.gradleProperty("lanternaVersion").get()
val jlineVersion: String = providers.gradleProperty("jlineVersion").get()

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    signing

    id("com.github.gmazzo.buildconfig") version "6.0.10"
    id("com.github.spotbugs") version "6.5.8"
}

buildConfig {
    className("Versions")
    packageName(group.toString())
    useJavaOutput()

    buildConfigField("String", "TETRUE_TERMINAL", "\"${project.version}\"")
    buildConfigField("String", "LANTERNA", "\"${lanternaVersion}\"")
    buildConfigField("String", "JLINE", "\"${jlineVersion}\"")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    implementation("org.jspecify:jspecify:1.0.0")
    implementation("org.apache.commons:commons-lang3:3.20.0")

    // Rendering Pipeline
    implementation("com.googlecode.lanterna:lanterna:${lanternaVersion}")
    implementation("org.jline:jline:$jlineVersion")

    // Logger
    implementation("org.apache.logging.log4j:log4j-api:2.26.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    withJavadocJar()
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])

            groupId = project.group.toString()
            artifactId = "tetrue-terminal"
            version = project.version.toString()

            versionMapping {
                usage("java-api") {
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime") {
                    fromResolutionResult()
                }
            }

            pom {
                name = "tetrue-terminal"
                description = "A meta library that combines JLine and Lanterna for my specific purposes"
                url = "https://github.com/BFUR64/tetrue-terminal"

                licenses {
                    license {
                        name = "MIT License"
                        url = "https://opensource.org/license/mit"
                    }
                }

                developers {
                    developer {
                        id = "BFUR64"
                        name = "Terrance"
                        url = "https://github.com/BFUR64/"
                    }
                }

                scm {
                    url = "https://github.com/BFUR64/tetrue-terminal"
                    connection = "scm:git:https://github.com/BFUR64/tetrue-terminal.git"
                    developerConnection = "scm:git:ssh://git@github.com/BFUR64/tetrue-terminal.git"
                }
            }
        }
    }
    repositories {
        maven {
            // change URLs to point to your repos, e.g. http://my.org/repo
            val releasesRepoUrl = uri(layout.buildDirectory.dir("repos/releases"))
            val snapshotsRepoUrl = uri(layout.buildDirectory.dir("repos/snapshots"))
            url = if (version.toString().endsWith("SNAPSHOT")) snapshotsRepoUrl else releasesRepoUrl
        }
    }

}

signing {
    val signingKey = file("signing-key.asc").readText()
    val signingPassword = project.findProperty("signingPassword") as String?

    useInMemoryPgpKeys(
        signingKey,
        signingPassword
    )

    sign(publishing.publications["mavenJava"])
}
